### ISSUE TITLE
"make all" fails: gsl_cdf.h not found

### ISSUE THREAD

**Issue by khoegenauer** [smithlabcode/preseq#13]
Occurs on install from github and v1.0.2 source tarball.
Error points to line 37 in preseq.cpp.
I presume this will present a similar problem for lines 38 and 39, as well.

Not that it should matter:
OS: Ubuntu 14.04 (Bio-Linux 8)
gcc: 4.8.2
gsl: 1.16

**Comment by timydaley** [comment]
Can I get the exact error?  From the information given, it seems that your compiler doesn't know where gsl is.

**Comment by khoegenauer** [comment]
Problem solved: Idiot-on-keyboard error.
Had to run make under the superuser (sudo), since /usr/include/gsl is owned by root. Also requires manually adding the binary location to the user's PATH.
Oddly enough, attempting to run the preseq binary -- which is owned by root -- using sudo returns "command not found", presumably because the root user has a different PATH. Running preseq without setting the PATH returns "permission denied"... go figure.

It may be beneficial to mention this in the user documentation or annotate the installation script, as the path to resolve the given error messages is not obvious for less-experienced users.

Somewhat unrelated:

1.) It is also not clear -- when samtools is already installed and in the PATH (e.g. Debian / brew package) -- if manually specifying it's path, when running make, is required. Judging from my install log, it looks like it isn't; however, I may be wrong. 

2.) Is anyone actively working on Galaxy integration  or a brew 'formula'?

**Comment by timydaley** [comment]
Thanks, I'll include some comments in the next release.  I'm working on adding some new stuff.  
Answers to the unrelated questions:
1.  I'll fix the Makefile for this.  This is a concern since we haven't updated to the most recent version of the samtools API, which is vastly different from the version we're using.
2.  We have an R package called preseqR available on CRAN (http://cran.r-project.org/web/packages/preseqR/index.html).  This is more for statisticians and doesn't have the option of taking mapped read files as input.  But sorry, we're not working on a Galaxy version at this time.
