### ISSUE TITLE
Installing preseq - 'samfile_t' does not name a type

### ISSUE THREAD

**Issue by lhogstrom** [smithlabcode/preseq#18]
Hi,

I am trying to build preseq on a linux machine. I've cloned the preseq repository and when I ran the 'make all' I was returned an error that there was no file matching 'smithlab_cpp//smithlab_os.o'. It seems like the the smithlab_cpp and preseqR directories have symbolic links to separate repos and did not contain any files when I cloned preseq. I've since populated these directories using the files from the respective repositories. 

I'm not sure if this is the correct approach, but now when run make all, I am returned this error:

<img width="693" alt="screenshot_10_7_15 _3_08_pm-2" src="https://cloud.githubusercontent.com/assets/3091474/10352218/c7290860-6d1b-11e5-988d-0003dc0f7d52.png">

Thanks for any tips!

**Comment by andrewdavidsmith** [comment]
Did u clone recursive?

**Comment by timydaley** [comment]
I think the problem is that you are linking to a local version of
samtools.  I also notice that you are linking to the bin directory.  The
version of samtools may be different from the one we use.  We use v0.1.16
and you are linking to v1.2.  There may have been major changes to the api
in meantime.  Can you set SAMTOOLS_DIR to the version we provide?

On Wed, Oct 7, 2015 at 2:58 PM, Larson Hogstrom <notifications@github.com>
wrote:

> Hi,
>
> I am trying to build preseq on a linux machine. I've cloned the preseq
> repository and when I ran the 'make all' I was returned an error that there
> was no file matching 'smithlab_cpp//smithlab_os.o'. It seems like the the
> smithlab_cpp and preseqR directories have symbolic links to separate repos
> and did not contain any files when I cloned preseq. I've since populated
> these directories using the files from the respective repositories.
>
> I'm not sure if this is the correct approach, but now when run make all, I
> am returned this error:
>
> [image: screenshot_10_7_15 _3_08_pm-2]
> <https://cloud.githubusercontent.com/assets/3091474/10352218/c7290860-6d1b-11e5-988d-0003dc0f7d52.png>
>
> Thanks for any tips!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smithlabcode/preseq/issues/18>.
>



-- 
Timothy Daley
University of Southern California

**Comment by lhogstrom** [comment]
Cloning recursive did the trick. Thank you.
