### ISSUE TITLE
Is preseq aware of UMI?

### ISSUE THREAD

**Issue by dnaase** [smithlabcode/preseq#33]
Hi,
Thanks a lot for this great tool! When preseq is predict the unique number of reads based on the complexity of reads, if there is UMI on one or both end of the reads, will it be aware of the existence of UMI?

thanks,

Yaping

**Comment by timydaley** [comment]
No, preseq does not look for UMIs.  There are too many protocols and UMIs can take varying length, so it is my opinion implementing a method to detect UMIs is well outside the scope of preseq.  However, if you can count duplicates then you can use either the counts as input into preseq using the -V flag, or the counts histogram using the -H flag.  
I have done this myself for some cases, but unfortunately that was a long time ago and I don't have those scripts anymore.  Sorry.

**Comment by timydaley** [comment]
Yaping, I thought you looked familiar.  You were in Ben Berman's lab, right?

**Comment by dnaase** [comment]
lol! Yes, i was from Berman lab and had a phd there~

**Comment by timydaley** [comment]
Awesome.  I'm closing the issue.  I'm sorry I don't have my scripts for when I did UMI counting, but if you're using something like the drop-seq computational protocol, it's easy to pick out the UMI and cell barcode from the sam file, and subsequently you can just count by position, UMI, and cell barcode with the command line.  
One thing I want to caution is that UMIs are typically put in the most error-prone part of the read.  Which is why some groups do UMI and cell barcode collapsing, merging reads that likely have an error in the UMI or cell barcode.  preseq will likely overestimate the true complexity if this is not taken into account.
