### ISSUE TITLE
Histogram input file 0 counts

### ISSUE THREAD

**Issue by isinaltinkaya** [smithlabcode/preseq#56]
Hi,

My histogram file contains 0 0 in the first line, e.g.:

```
0       0
1       60833379
2       26578973
3       9192783
4       2756185
5       767258
...
```

In the example you have provided in the manual I saw that your example starts with 1. I tried both and got the exact same results for lc_extrap. I have been using the histogram with 0's for a while now. Do you think it is necessary to repeat all these preseq runs with deleting the first line of histogram, or can I assume I would get the same output?

Thank you,

**Comment by terencewtli** [comment]
Hi,

Thank you for bringing this up! I have never seen this before, but I've tested this on our test data and you are correct. I'd go ahead and keep the `preseq` runs with the 0's, and I'll add this to the documentation.

**Comment by andrewdavidsmith** [comment]
@isinaltinkaya @terencewtli I'm reopening this issue just to clarify something. I looked into the code just now, and as I suspected, the internals of the computation actually create an entry in the histogram for "0" when it is not present. This makes all the computation more convenient. So in your case everything should be fine. The only problem on our end is that this could allow for someone to insert a non-zero count for things observed zero times... which actually impacts the estimates. So @isinaltinkaya you are ok doing what you have done, but I think we will update the code so that in the future you will not be able to use any line with `0` as the starting count, since we can't guarantee that someone won't insert a non-zero beside it.

**Comment by andrewdavidsmith** [comment]
We have updated the code in the repo to prevent possible issues around this, and the next release will include those changes. Thanks again @isinaltinkaya

**Comment by isinaltinkaya** [comment]
> We have updated the code in the repo to prevent possible issues around this, and the next release will include those changes. Thanks again @isinaltinkaya

Thanks! Will you ignore the lines starting with 0 or will you throw an error and exit? We may need to change our pipeline if you plan the latter to ensure compatibility with new versions. As a user, I would prefer if you ignore the lines starting with 0. Also if there are other people using similar histogram inputs they wouldn't start getting errors with the new version.

Thanks again!
